apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hz
  labels:
    app.kubernetes.io/name: hazelcast
    app.kubernetes.io/instance: hazelcast
    app.kubernetes.io/managed-by: hazelcast-operator
spec:
  image:
    repository: "hazelcast/hazelcast"
    tag: 4.0.3
  service:
    create: true
    type: ClusterIP
    clusterIP: "None"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
  resources:
    requests:
      memory: 1024Mi
      cpu: 100m
    limits:
      memory: 1024Mi
  securityContext:
    runAsUser: ""
    runAsGroup: ""
    fsGroup: ""
  mancenter:
    image:
      repository: "hazelcast/management-center"
      tag: 4.2020.08
    enabled: true
    service:
      type: LoadBalancer
      port: 8080
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: beta.kubernetes.io/arch
              operator: In
              values:
              - amd64
    resources:
      requests:
        memory: 1024Mi
        cpu: 100m
      limits:
        memory: 1024Mi
  rbac:
    create: false
  serviceAccount:
    create: false
    name: hazelcast
