---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hazelcastenterprises.hazelcast.com
spec:
  group: hazelcast.com
  names:
    kind: HazelcastEnterprise
    listKind: HazelcastEnterpriseList
    plural: hazelcastenterprises
    singular: hazelcastenterprise
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  subresources:
    status: {}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hazelcast-enterprise-operator
  labels:
    app.kubernetes.io/name: hazelcast-enterprise-operator
    app.kubernetes.io/instance: hazelcast-enterprise-operator
    app.kubernetes.io/managed-by: hazelcast-enterprise-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hazelcast-enterprise-operator
  labels:
    app.kubernetes.io/name: hazelcast-enterprise-operator
    app.kubernetes.io/instance: hazelcast-enterprise-operator
    app.kubernetes.io/managed-by: hazelcast-enterprise-operator
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
    verbs:
    - '*'
  - apiGroups:
    - ""
    - "extensions"
    resources:
    - ingresses
    verbs:
    - '*'
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - serviceaccounts
    verbs:
    - get
    - create
    - list
    - update
    - delete
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - roles
    - rolebindings
    verbs:
    - get
    - create
    - list
    - update
    - delete
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    verbs:
    - '*'
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    verbs:
    - get
    - create
  - apiGroups:
    - apps
    resourceNames:
    - hazelcast-enterprise-operator
    resources:
    - deployments/finalizers
    verbs:
    - update
  - apiGroups:
    - hazelcast.com
    resources:
    - '*'
    verbs:
    - '*'

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hazelcast-enterprise-operator
  labels:
    app.kubernetes.io/name: hazelcast-enterprise-operator
    app.kubernetes.io/instance: hazelcast-enterprise-operator
    app.kubernetes.io/managed-by: hazelcast-enterprise-operator
subjects:
- kind: ServiceAccount
  name: hazelcast-enterprise-operator
roleRef:
  kind: ClusterRole
  name: hazelcast-enterprise-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-enterprise-operator
  labels:
    app.kubernetes.io/name: hazelcast-enterprise-operator
    app.kubernetes.io/instance: hazelcast-enterprise-operator
    app.kubernetes.io/managed-by: hazelcast-enterprise-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hazelcast-enterprise-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hazelcast-enterprise-operator
        app.kubernetes.io/instance: hazelcast-enterprise-operator
        app.kubernetes.io/managed-by: hazelcast-enterprise-operator
      annotations:
        productID: hazelcast-enterprise-operator
        productName: Hazelcast Enterprise Operator
        productVersion: 0.3.4-1
    spec:
      serviceAccountName: hazelcast-enterprise-operator
      securityContext:
        capabilities:
          drop:
          - ALL
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
        - name: hazelcast-enterprise-operator
          image: registry.connect.redhat.com/hazelcast/hazelcast-enterprise-operator:0.3.4-1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hazelcast-enterprise-operator"
            - name: RELATED_IMAGE_HAZELCAST
              value: registry.connect.redhat.com/hazelcast/hazelcast-enterprise-4-rhel8:4.1.1
            - name: RELATED_IMAGE_MANCENTER
              value: registry.connect.redhat.com/hazelcast/management-center-4-rhel8:4.2020.12-2
          resources:
            limits:
              cpu: "0.1"
              memory: 512Mi
            requests:
              cpu: "0.1"
              memory: 256Mi
