apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hazelcastenterprises.hazelcast.com
  labels:
    app.kubernetes.io/name: hazelcast
    app.kubernetes.io/instance: hazelcast
    app.kubernetes.io/managed-by: hazelcast-enterprise-operator
spec:
  group: hazelcast.com
  names:
    kind: HazelcastEnterprise
    listKind: HazelcastEnterpriseList
    plural: hazelcastenterprises
    singular: hazelcastenterprise
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
