apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-enterprise-operator
  labels:
    app.kubernetes.io/name: hazelcast-enterprise-operator
    app.kubernetes.io/instance: hazelcast-enterprise-operator
    app.kubernetes.io/managed-by: hazelcast-enterprise-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hazelcast-enterprise-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hazelcast-enterprise-operator
        app.kubernetes.io/instance: hazelcast-enterprise-operator
        app.kubernetes.io/managed-by: hazelcast-enterprise-operator
      annotations:
        productID: hazelcast-enterprise-operator
        productName: Hazelcast Enterprise Operator
        productVersion: 0.3.3
    spec:
      serviceAccountName: hazelcast-enterprise-operator
      securityContext:
        capabilities:
          drop:
          - ALL
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
        - name: hazelcast-enterprise-operator
          image: registry.connect.redhat.com/hazelcast/hazelcast-enterprise-operator:0.3.3
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hazelcast-enterprise-operator"
            - name: HAZELCAST_IMAGE_REPOSITORY
              value: registry.connect.redhat.com/hazelcast/hazelcast-enterprise-4-rhel8
            - name: HAZELCAST_IMAGE_TAG
              value: 4.0.3-1
            - name: MC_IMAGE_REPOSITORY
              value: registry.connect.redhat.com/hazelcast/management-center-4-rhel8
            - name: MC_IMAGE_TAG
              value: 4.2020.08-1
          resources:
            limits:
              cpu: "0.1"
              memory: 512Mi
            requests:
              cpu: "0.1"
              memory: 256Mi
