apiVersion: v1
data:
  key: <base64-hz-license-key>
kind: Secret
metadata:
  name: hz-license-key-secret
  labels:
    app.kubernetes.io/name: hazelcast
    app.kubernetes.io/instance: hazelcast
    app.kubernetes.io/managed-by: hazelcast-enterprise-operator
